CREATE TABLE LIST (
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	TITLE VARCHAR2(200), 
	DESCRIPTION VARCHAR2(500)
);

CREATE TABLE ITEM (
	ID INT AUTO_INCREMENT PRIMARY KEY, 
	CREATION DATETIME, 
	LAST_MODIFICATION DATETIME, 
	TITLE VARCHAR2(200), 
	DESCRIPTION VARCHAR2(500),
	STATE VARCHAR2(10) DEFAULT 'TODO',
	LIST_ID INT NOT NULL,
	FOREIGN KEY (LIST_ID) 
	REFERENCES LIST(ID)
	ON DELETE CASCADE
);

CREATE TABLE ACCOUNT (
    ID INT AUTO_INCREMENT PRIMARY KEY, 
    USERNAME VARCHAR2(50) NOT NULL,
    PASSWORD VARCHAR2(100) NOT NULL,
    MAIL VARCHAR2(100) NOT NULL
);

CREATE ROLE User;
GRANT all ON List TO User;
GRANT all ON Item TO User;
GRANT all ON Account TO User;

CREATE USER Kay PASSWORD 'dop';
GRANT User TO Kay;

COMMIT;
